@startuml

title __TEMPLATE's Class Diagram__\n

  namespace es.ull.patrones {
    namespace es.ull.patrones.template {
      class es.ull.patrones.template.Problem {
          ~ problem : ArrayList<Double>
          + Problem()
          + Problem()
          + getElement()
          + getProblem()
          + getSize()
          + setElement()
          + setElement()
          + setProblem()
          + write()
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones.template {
      interface es.ull.patrones.template.ProblemInterface {
          {abstract} + getElement()
          {abstract} + getProblem()
          {abstract} + getSize()
          {abstract} + setElement()
          {abstract} + setElement()
          {abstract} + setProblem()
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones.template {
      class es.ull.patrones.template.Solution {
          ~ solution : ArrayList<Double>
          + Solution()
          + getElement()
          + getSize()
          + getSolution()
          + setElement()
          + setElement()
          + setSolution()
          + write()
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones.template {
      interface es.ull.patrones.template.SolutionInterface {
          {abstract} + getElement()
          {abstract} + getSize()
          {abstract} + getSolution()
          {abstract} + setElement()
          {abstract} + setElement()
          {abstract} + setSolution()
      }
    }
  }
  

  es.ull.patrones.template.Problem .up.|> es.ull.patrones.template.ProblemInterface
  es.ull.patrones.template.Solution .up.|> es.ull.patrones.template.SolutionInterface


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
